version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081

  rabbitmq:
    image: rabbitmq
    restart: always
    ports:
      - 5672:5672

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  minio:
    image: minio/minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
    command: server /data
    ports:
      - 9000:9000

  flask:
    build:
      context: .
      dockerfile: flask.Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 5000:80
    links:
      - mongo
      - rabbitmq
      - redis
      - minio

  celery:
    build:
      context: .
      dockerfile: celery.Dockerfile
    restart: always
    env_file:
      - .env
    links:
      - mongo
      - rabbitmq
      - redis
      - minio